global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
scrape_configs:

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'department'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9001' ]
  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9002' ]