server:
  port: 9999

#demo:
#  service:
#    url: http://localhost:8080
spring:
  application:
    name: MS-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
      routes:
        - id: MS-USER
          uri: lb://ms-user
          predicates:
            - Path=/users/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: MS-USER
#                fallbackUri: forward:/ms-user-fallback
        - id: MS-DEPARTMENT
          uri: lb://ms-department
          predicates:
            - Path=/departments/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: MS-DEPARTMENT
#                fallbackUri: forward:/ms-department-fallback

eureka:
  client:
#    register-with-eureka: true
#    fecth-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.application.name}:${random.uuid}

# actuator
management:
  endpoint:
    health:
      status:
        http-mapping:
          down: 500
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG