server:
  port: 9999
spring:
  application:
    name: MS-GATEWAY
  cloud:
    config:
      import: "optional: configserver: http://localhost:9000?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100/"
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
      routes:
        - id: MS-USER
          uri: lb://ms-user
          predicates:
            - Path=/users/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: MS-USER
#                fallbackUri: forward:/ms-user-fallback
        - id: MS-DEPARTMENT
          uri: lb://ms-department
          predicates:
            - Path=/departments/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: MS-DEPARTMENT
#                fallbackUri: forward:/ms-department-fallback

# actuator
management:
  endpoint:
    health:
      status:
        http-mapping:
          down: 500
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG