server:
  port: 9002
spring:
  application:
    name: MS-USER
  cloud:
  config:
    import: "optional: configserver: http://localhost:9000?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100/"
